name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies with Launchpad
        uses: stacksjs/launchpad-installer@v1
        with:
          packages: node typescript bun # Space-separated list of packages

      - name: Run build
        run: |
          which node
          which typescript
          bun --version
          bun run build
