name: Custom Config Setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies from custom config file
        uses: stacksjs/bumpx-installer@v1
        with:
          config-path: .github/bumpx/production.config.ts

      - name: Deploy application
        run: |
          # All packages from the custom config are now available
          bumpx list

          # Run deployment commands
          bun run deploy
